#!/usr/bin/env sh
[ ! -f .env ] && echo "✗ .env file not found" && exit 1

. ./.env

echo "Building Docker image to validate..."

docker build -t rent-management-system:latest . \
  --build-arg "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" \
  --quiet || { echo "✗ Docker build failed. Ensure Docker is running."; exit 1; }

echo "✓ Docker image built successfully."
